logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true

    hibernate:
      ddl-auto: create

oauth:
  kakao:
    client_id: 44f2490daa92e50822ad519ef4b33451
    redirect_uri: http://localhost:3000/oauth/redirected/kakao
    client_secret: LdEFfOMgUKZnLoCT3VSBSw5b3coO17Qp
    scope: profile_nickname, profile_image
